all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local 
      webservers:
        hosts:
          web1.local:
           ansible_connection: local
          web2.local:
            ansible_connection: local
        vars: 
          http_port: 8080
